name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        # Install Tesseract OCR
        choco install tesseract
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # Install your project dependencies
        pip install opencv-python
        pip install PyQt5
        pip install pandas
        pip install openpyxl
        pip install pytesseract
        pip install numpy
        
    - name: Build Complete Package
      run: |
        # Build using the comprehensive spec file
        pyinstaller TimeStudyAnalyzer.spec
        
    - name: Create distribution package
      run: |
        mkdir TimeStudyAnalyzer-Complete-Package
        
        # Copy executables
        copy "dist\TimeStudyAnalyzer-Complete\TimeStudyAnalyzer-GUI.exe" "TimeStudyAnalyzer-Complete-Package\"
        copy "dist\TimeStudyAnalyzer-Complete\TimeStudyAnalyzer-CLI.exe" "TimeStudyAnalyzer-Complete-Package\"
        
        # Copy user resources
        copy "Que Cards.pptx" "TimeStudyAnalyzer-Complete-Package\"
        copy "User-Guide.md" "TimeStudyAnalyzer-Complete-Package\"
        copy "README.md" "TimeStudyAnalyzer-Complete-Package\"
        copy "requirements.txt" "TimeStudyAnalyzer-Complete-Package\"
        
        # Copy templates folder
        xcopy "templates" "TimeStudyAnalyzer-Complete-Package\templates\" /E /I
        
        # Create ZIP for easy distribution
        Compress-Archive -Path "TimeStudyAnalyzer-Complete-Package\*" -DestinationPath "TimeStudyAnalyzer-Complete-Package.zip"
        
    - name: Upload Complete Package
      uses: actions/upload-artifact@v3
      with:
        name: TimeStudyAnalyzer-Complete-Package
        path: TimeStudyAnalyzer-Complete-Package/
        
    - name: Upload Complete Package ZIP
      uses: actions/upload-artifact@v3
      with:
        name: TimeStudyAnalyzer-Complete-ZIP
        path: TimeStudyAnalyzer-Complete-Package.zip
        
    # Auto-create release on version tags
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/cli/TimeStudyAnalyzer-CLI.exe
          dist/gui/TimeStudyAnalyzer-GUI.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
