name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  create-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        choco install tesseract
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Update version in code
      run: |
        # Update version in analyze_cards.py
        (Get-Content src/analyzer/analyze_cards.py) -replace '__version__ = .*', "__version__ = '${{ github.event.inputs.version }}'" | Set-Content src/analyzer/analyze_cards.py
        
    - name: Build complete package with version info
      run: |
        # Build using comprehensive spec file
        pyinstaller TimeStudyAnalyzer.spec
        
    - name: Create versioned release package
      run: |
        # Create main release folder
        mkdir "TimeStudyAnalyzer-${{ github.event.inputs.version }}"
        
        # Copy executables with version names
        copy "dist\TimeStudyAnalyzer-Complete\TimeStudyAnalyzer-GUI.exe" "TimeStudyAnalyzer-${{ github.event.inputs.version }}\TimeStudyAnalyzer-GUI-${{ github.event.inputs.version }}.exe"
        copy "dist\TimeStudyAnalyzer-Complete\TimeStudyAnalyzer-CLI.exe" "TimeStudyAnalyzer-${{ github.event.inputs.version }}\TimeStudyAnalyzer-CLI-${{ github.event.inputs.version }}.exe"
        
        # Copy user resources
        copy "Que Cards.pptx" "TimeStudyAnalyzer-${{ github.event.inputs.version }}\"
        copy "User-Guide.md" "TimeStudyAnalyzer-${{ github.event.inputs.version }}\"
        copy "README.md" "TimeStudyAnalyzer-${{ github.event.inputs.version }}\"
        copy "requirements.txt" "TimeStudyAnalyzer-${{ github.event.inputs.version }}\"
        
        # Copy templates folder
        xcopy "templates" "TimeStudyAnalyzer-${{ github.event.inputs.version }}\templates\" /E /I
        
        # Create installation instructions
        echo "# Quick Start Instructions" > "TimeStudyAnalyzer-${{ github.event.inputs.version }}\INSTALL.md"
        echo "" >> "TimeStudyAnalyzer-${{ github.event.inputs.version }}\INSTALL.md"
        echo "1. Print 'Que Cards.pptx' on a color printer" >> "TimeStudyAnalyzer-${{ github.event.inputs.version }}\INSTALL.md"
        echo "2. Install Tesseract OCR from: https://github.com/UB-Mannheim/tesseract/wiki" >> "TimeStudyAnalyzer-${{ github.event.inputs.version }}\INSTALL.md"
        echo "3. Run TimeStudyAnalyzer-GUI-${{ github.event.inputs.version }}.exe" >> "TimeStudyAnalyzer-${{ github.event.inputs.version }}\INSTALL.md"
        echo "4. See User-Guide.md for detailed instructions" >> "TimeStudyAnalyzer-${{ github.event.inputs.version }}\INSTALL.md"
        
        # Create ZIP file
        Compress-Archive -Path "TimeStudyAnalyzer-${{ github.event.inputs.version }}" -DestinationPath "TimeStudyAnalyzer-${{ github.event.inputs.version }}-Complete.zip"
        
    - name: Create Git tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag ${{ github.event.inputs.version }}
        git push origin ${{ github.event.inputs.version }}
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: "Time Study Analyzer ${{ github.event.inputs.version }}"
        body: |
          ## Time Study Analyzer ${{ github.event.inputs.version }}
          
          ### Downloads
          - **Complete Package**: `TimeStudyAnalyzer-${{ github.event.inputs.version }}-Complete.zip` - **RECOMMENDED** - Everything you need to get started
          - **GUI Version**: `TimeStudyAnalyzer-GUI-${{ github.event.inputs.version }}.exe` - Graphical user interface only
          - **CLI Version**: `TimeStudyAnalyzer-CLI-${{ github.event.inputs.version }}.exe` - Command line interface only
          
          ### What's in the Complete Package
          - Both GUI and CLI executables
          - **Que Cards.pptx** - Printable colored cards for time study
          - **User-Guide.md** - Step-by-step setup instructions
          - **Templates** - Pre-configured card detection files
          - **Documentation** - Complete usage guide
          
          ### Features
          - Multi-resolution video processing (360p, 720p, 1080p)
          - Real-time card detection for START, STOP, DOWN, LOOK, and MEETING cards
          - Optimized CPU usage (60% of available cores)
          - Excel reporting with comprehensive timing analysis
          - Multi-threaded processing for improved performance
          
          ### Requirements
          - Windows 10/11
          - Tesseract OCR (for text recognition)
          
          Built automatically from commit: ${{ github.sha }}
        files: |
          TimeStudyAnalyzer-${{ github.event.inputs.version }}-Complete.zip
          dist/TimeStudyAnalyzer-Complete/TimeStudyAnalyzer-GUI.exe
          dist/TimeStudyAnalyzer-Complete/TimeStudyAnalyzer-CLI.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
